plugins {
    id 'java'
    id 'maven-publish'
}

group 'com.hrzc.lib.tools'
version '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

ext{
    git_token=System.getenv("TOOLS_DT")
}

publishing {
    publications {
        library(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "https://gitlab.com/api/v4/projects/46638027/packages/maven"
            credentials(HttpHeaderCredentials) {
                name = "Deploy-Token"
                value = git_token
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}

repositories {
    mavenCentral()
}

