plugins {
    id 'java'
    id 'maven-publish'
}

group 'com.hhrzc.lib.tools'
version '0.0.3-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    git_token = System.getenv("TOOLS_DT")
}

print(git_token)

publishing {
    publications {
        library(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "https://gitlab.com/api/v4/projects/47009346/packages/maven"
            credentials(HttpHeaderCredentials) {
                name = "Deploy-Token"
                value = git_token
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}
